plugins {
    id "com.android.application"
}

android {
    namespace "com.securevault.app"
    compileSdk 35

    defaultConfig {
        applicationId "com.securevault.app"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}


dependencies {
    implementation "androidx.core:core:1.15.0"
}
